INFO     root:entity.py:43 Unable to find a row with primary key 18ef5975-7fe1-478c-b277-a0248486a683, in Collection table.